#SET histogram_generation_max_mem_size = 2000000000;
#UPDATE performance_schema.setup_consumers SET enabled='YES' WHERE NAME = 'events_statements_history_long';
#TRUNCATE performance_schema.events_statements_history_long;
ANALYZE TABLE customer UPDATE HISTOGRAM ON c_acctbal;
ANALYZE TABLE customer UPDATE HISTOGRAM ON c_address;
ANALYZE TABLE customer UPDATE HISTOGRAM ON c_comment;
ANALYZE TABLE customer UPDATE HISTOGRAM ON c_mktsegment;
ANALYZE TABLE customer UPDATE HISTOGRAM ON c_name;
ANALYZE TABLE customer UPDATE HISTOGRAM ON c_nationkey;
ANALYZE TABLE customer UPDATE HISTOGRAM ON c_phone;
ANALYZE TABLE lineitem UPDATE HISTOGRAM ON l_commitdate;
ANALYZE TABLE lineitem UPDATE HISTOGRAM ON l_discount;
ANALYZE TABLE lineitem UPDATE HISTOGRAM ON l_extendedprice;
ANALYZE TABLE lineitem UPDATE HISTOGRAM ON l_linestatus;
ANALYZE TABLE lineitem UPDATE HISTOGRAM ON l_orderkey;
ANALYZE TABLE lineitem UPDATE HISTOGRAM ON l_partkey;
ANALYZE TABLE lineitem UPDATE HISTOGRAM ON l_quantity;
ANALYZE TABLE lineitem UPDATE HISTOGRAM ON l_receiptdate;
ANALYZE TABLE lineitem UPDATE HISTOGRAM ON l_returnflag;
ANALYZE TABLE lineitem UPDATE HISTOGRAM ON l_shipdate;
ANALYZE TABLE lineitem UPDATE HISTOGRAM ON l_shipinstruct;
ANALYZE TABLE lineitem UPDATE HISTOGRAM ON l_shipmode;
ANALYZE TABLE lineitem UPDATE HISTOGRAM ON l_suppkey;
ANALYZE TABLE lineitem UPDATE HISTOGRAM ON l_tax;
ANALYZE TABLE nation UPDATE HISTOGRAM ON n_name;
ANALYZE TABLE nation UPDATE HISTOGRAM ON n_regionkey;
ANALYZE TABLE orders UPDATE HISTOGRAM ON o_comment ;
ANALYZE TABLE orders UPDATE HISTOGRAM ON o_custkey;
ANALYZE TABLE orders UPDATE HISTOGRAM ON o_orderdate;
ANALYZE TABLE orders UPDATE HISTOGRAM ON o_orderpriority;
ANALYZE TABLE orders UPDATE HISTOGRAM ON o_orderstatus;
ANALYZE TABLE orders UPDATE HISTOGRAM ON o_shippriority;
ANALYZE TABLE orders UPDATE HISTOGRAM ON o_totalprice;
ANALYZE TABLE part UPDATE HISTOGRAM ON p_brand;
ANALYZE TABLE part UPDATE HISTOGRAM ON p_container;
ANALYZE TABLE part UPDATE HISTOGRAM ON p_mfgr;
ANALYZE TABLE part UPDATE HISTOGRAM ON p_name;
ANALYZE TABLE part UPDATE HISTOGRAM ON p_size;
ANALYZE TABLE part UPDATE HISTOGRAM ON p_type;
ANALYZE TABLE partsupp UPDATE HISTOGRAM ON ps_availqty;
ANALYZE TABLE partsupp UPDATE HISTOGRAM ON ps_partkey;
ANALYZE TABLE partsupp UPDATE HISTOGRAM ON ps_suppkey;
ANALYZE TABLE partsupp UPDATE HISTOGRAM ON ps_supplycost;
ANALYZE TABLE region UPDATE HISTOGRAM ON r_name;
ANALYZE TABLE supplier UPDATE HISTOGRAM ON s_acctbal;
ANALYZE TABLE supplier UPDATE HISTOGRAM ON s_address;
ANALYZE TABLE supplier UPDATE HISTOGRAM ON s_comment;
ANALYZE TABLE supplier UPDATE HISTOGRAM ON s_name;
ANALYZE TABLE supplier UPDATE HISTOGRAM ON s_nationkey;
ANALYZE TABLE supplier UPDATE HISTOGRAM ON s_phone;
#SELECT sql_text, timer_wait/1000000000000.0 "Time (s)"
#FROM performance_schema.events_statements_history_long;
