select count(*) from supplier;
select count(*) from part;
select count(*) from partsupp;
select count(*) from customer;
select count(*) from orders;
select count(*) from lineitem;
select count(*) from nation;
select count(*) from region;
select count(distinct s_nationkey) from supplier;
select count(distinct ps_partkey) from partsupp;
select count(distinct ps_suppkey) from partsupp;
select count(distinct c_nationkey) from customer;
select count(distinct o_custkey) from orders;
select count(distinct o_orderdate) from orders;
select count(distinct l_orderkey) from lineitem;
select count(distinct l_partkey) from lineitem;
select count(distinct l_suppkey) from lineitem;
select count(distinct concat(l_partkey, l_suppkey)) from lineitem;
select count(distinct l_shipdate) from lineitem;
select count(distinct n_regionkey) from nation;
