#!/bin/bash -x
set -e

SF=$1
RESDIR=$2
DB=dbt3_sf${SF}

/usr/pgsql-13/bin/pg_ctl start -D /var/lib/pgsql/13/data
./bind-postgres

# Warm-up
psql -d $DB < preload-withindex-pg.sql > /dev/null

python multiq-postgres.py dbt3-pg $SF 10 $RESDIR

/usr/pgsql-13/bin/pg_ctl stop -D /var/lib/pgsql/13/data

python multiq-result.py dbt3 $SF $RESDIR
cat results-sf${SF}/${RESDIR}/res_default.csv

